services:
  db:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=testpass
      - MYSQL_DATABASE=default
    volumes:
    - devmysqldb:/var/lib/mysql

  web: 
    build: app 
    depends_on:
      - db
    restart: always
    volumes:
      - ./app:/app
      - type: bind
        source: ./starlink_historical_data.json
        target: /data.json
    stdin_open: true # enable attach for pdb
    tty: true
    ports: 
      - '5000:5000'
volumes:
  devmysqldb: